global:
  resolve_timeout: 5m
  slack_api_url: 'real_web_hook!'

route:
  receiver: 'email-receiver'
  routes:
    - receiver: 'slack-alerts'
      group_wait: 10s
      group_interval: 5m
      repeat_interval: 3h
      matchers:
        - severity="critical"

receivers:
  - name: 'email-receiver'
    email_configs:
      - to: 'myemail'
        from: 'email'
        smarthost: 'smtp.gmail.com:587'
        require_tls: true
        auth_username: 'email'
        auth_password: 'my_password -.-'
        send_resolved: true

  - name: 'slack-alerts'
    slack_configs:
      - channel: '#security-alerts'
        send_resolved: true
        title: "🚨 Prometheus Alert:"
        text: "ALERT"
