global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
    - targets: ['10.0.0.192:9100']


alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - localhost:9093


rule_files:
  - "alert_rules.yml"  # Reference the alert rule file
